CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# ECG Model Constants
IGNORE_INDEX = -100
ECG_TOKEN_INDEX = -201
DEFAULT_ECG_TOKEN = "<ecg>"
DEFAULT_ECG_PATCH_TOKEN = "<ecg_patch>"
DEFAULT_ECG_START_TOKEN = "<ecg_start>"
DEFAULT_ECG_END_TOKEN = "<ecg_end>"
ECG_PLACEHOLDER = "<ecg-placeholder>"
